### ISSUE TITLE
Why is repogitory url specifies "git://" ?

### ISSUE THREAD

**Issue by hiroki-uchida** [TooTallNate/node-pac-proxy-agent#24]
https://github.com/TooTallNate/node-pac-proxy-agent/blob/master/package.json#L11

```
  "repository": {
    "type": "git",
    "url": "git://github.com/TooTallNate/node-pac-proxy-agent.git"
  },
```

In an environment without Git, the following error appears.

```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/snyk/node-https-proxy-agent.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

I see a repository url with `git://` for the first time.
If you have a reason for `git://`, I think you need to write in the `README.md`, including the need to install Git.

**Comment by TooTallNate** [comment]
The error that you are seeing is not related to that `url` field in the package.json. `git://github.com/snyk/node-https-proxy-agent.git` is a fork from `snyk`, it was probably being specified by one of your dependencies. I think that fork is no longer relevant as the security issue that it was created for has since been fixed.

Closing, but let me know if you're still having troubles with this.
